# Generated by Django 6.0.7 on 2026-08-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="images",
        ),
        migrations.RemoveField(
            model_name="model",
            name="images",
        ),
        migrations.AddField(
            model_name="asset",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.image",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="models",
                to="assets.image",
            ),
        ),
    ]
