# Generated by Django 6.0.7 on 2026-08-05 01:45

from django.db import migrations, models

import assets.models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_remove_asset_images_remove_model_images_asset_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                blank=True,
                choices=assets.models.asset_category_choices,
                max_length=255,
                null=True,
            ),
        ),
    ]
