# Generated by Django 6.0.7 on 2026-08-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_owner_asset_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.owner",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("name", "manufacturer"), name="unique_model_name_manufacturer"
            ),
        ),
    ]
