# Generated by Django 6.0.7 on 2026-08-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_asset_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Auto-selected as the owner when creating a new asset.",
            ),
        ),
    ]
