# Generated by Django 6.0.7 on 2026-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_asset_owner_alter_model_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
