# Generated by Django 6.0.7 on 2026-08-06 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'RFID scanner script'",
                        max_length=255,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "hashed_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
